objectName: Master_Framework_c
properties:
  rmNumber: RM_Number__c
  salesforceId: Id
  title: Long_Name__c
  terms: Framework_Terms__c
  pillar: Pillar__c
  category: CCS_Sub_Category_Text__c
  status: Status__c
  startDate: Start_Date__c
  endDate: Effective_End_Date__c
  tendersOpenDate: OJEU_Date_Target__c
  tendersCloseDate: Tender_Closing_Date__c
  expectedLiveDate: Framework_Live_Date_Target__c
  expectedAwardDate: Award_Date_Target__c
