objectName: Master_Framework_Lot__c
properties:
  salesforceId: Id
  frameworkId: Master_Framework__c
  lotNumber: Master_Framework_Lot_Number__c
  title: Name
  status: Status__c
  expiryDate: Expiry_Date__c
